### ISSUE TITLE
Error - Slice bounds out of range

### ISSUE THREAD

**Issue by lewpayne** [Nitecon/iqfeed#2]
Running your iqfeed_example yields the following under Win 10:

> C:\Users\lewpa\go\src\github.com\Nitecon\iqfeed_example>go run main.go
> System: &iqfeed.SystemMessage{Customer:iqfeed.CustomerData{ServiceType:"", IP:"", Port:0, Token:"", Version:"", Deprecated1:0, VerboseExchanges:"", Deprecated2:"", MaxSymbols:0, Flags:"", Deprecated3:"", Deprecated4:""}, Stats:iqfeed.SystemStats{ServerIP:"", ServerPort:0, MaxSymbols:0, NumberOfSymbols:0, ClientsConnected:0, SecondsSinceLastUpdate:0, Reconnections:0, AttemptedReconnections:0, StartTime:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, MarketTime:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, Status:"", IQFeedVersion:"", LoginID:"", TotalKBsRecv:0, KBsPerSecRecv:0, AvgKBsPerSecRecv:0, TotalKBsSent:0, KBsPerSecSent:0, AvgKBsPerSecSent:0}}
> System: &iqfeed.SystemMessage{Customer:iqfeed.CustomerData{ServiceType:"", IP:"", Port:0, Token:"", Version:"", Deprecated1:0, VerboseExchanges:"", Deprecated2:"", MaxSymbols:0, Flags:"", Deprecated3:"", Deprecated4:""}, Stats:iqfeed.SystemStats{ServerIP:"", ServerPort:0, MaxSymbols:0, NumberOfSymbols:0, ClientsConnected:0, SecondsSinceLastUpdate:0, Reconnections:0, AttemptedReconnections:0, StartTime:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, MarketTime:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, Status:"", IQFeedVersion:"", LoginID:"", TotalKBsRecv:0, KBsPerSecRecv:0, AvgKBsPerSecRecv:0, TotalKBsSent:0, KBsPerSecSent:0, AvgKBsPerSecSent:0}}
> System: &iqfeed.SystemMessage{Customer:iqfeed.CustomerData{ServiceType:"", IP:"", Port:0, Token:"", Version:"", Deprecated1:0, VerboseExchanges:"", Deprecated2:"", MaxSymbols:0, Flags:"", Deprecated3:"", Deprecated4:""}, Stats:iqfeed.SystemStats{ServerIP:"", ServerPort:0, MaxSymbols:0, NumberOfSymbols:0, ClientsConnected:0, SecondsSinceLastUpdate:0, Reconnections:0, AttemptedReconnections:0, StartTime:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, MarketTime:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, Status:"", IQFeedVersion:"", LoginID:"", TotalKBsRecv:0, KBsPerSecRecv:0, AvgKBsPerSecRecv:0, TotalKBsSent:0, KBsPerSecSent:0, AvgKBsPerSecSent:0}}
> System: &iqfeed.SystemMessage{Customer:iqfeed.CustomerData{ServiceType:"", IP:"", Port:0, Token:"", Version:"", Deprecated1:0, VerboseExchanges:"", Deprecated2:"", MaxSymbols:0, Flags:"", Deprecated3:"", Deprecated4:""}, Stats:iqfeed.SystemStats{ServerIP:"", ServerPort:0, MaxSymbols:0, NumberOfSymbols:0, ClientsConnected:0, SecondsSinceLastUpdate:0, Reconnections:0, AttemptedReconnections:0, StartTime:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, MarketTime:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, Status:"", IQFeedVersion:"", LoginID:"", TotalKBsRecv:0, KBsPerSecRecv:0, AvgKBsPerSecRecv:0, TotalKBsSent:0, KBsPerSecSent:0, AvgKBsPerSecSent:0}}
> System: &iqfeed.SystemMessage{Customer:iqfeed.CustomerData{ServiceType:"", IP:"", Port:0, Token:"", Version:"", Deprecated1:0, VerboseExchanges:"", Deprecated2:"", MaxSymbols:0, Flags:"", Deprecated3:"", Deprecated4:""}, Stats:iqfeed.SystemStats{ServerIP:"", ServerPort:0, MaxSymbols:0, NumberOfSymbols:0, ClientsConnected:0, SecondsSinceLastUpdate:0, Reconnections:0, AttemptedReconnections:0, StartTime:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, MarketTime:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, Status:"", IQFeedVersion:"", LoginID:"", TotalKBsRecv:0, KBsPerSecRecv:0, AvgKBsPerSecRecv:0, TotalKBsSent:0, KBsPerSecSent:0, AvgKBsPerSecSent:0}}
> panic: runtime error: slice bounds out of range

```
goroutine 20 [running]:
github.com/Nitecon/iqfeed.(*IQC).processReceiver(0xc00008c000, 0xc0000b2978, 0x0, 0x688)
        C:/Users/lewpa/go/src/github.com/Nitecon/iqfeed/iqfeed.go:141 +0x32f
github.com/Nitecon/iqfeed.(*IQC).read(0xc00008c000)
        C:/Users/lewpa/go/src/github.com/Nitecon/iqfeed/iqfeed.go:181 +0x1a6
created by github.com/Nitecon/iqfeed.(*IQC).Start
        C:/Users/lewpa/go/src/github.com/Nitecon/iqfeed/iqfeed.go:268 +0x1d0
exit status 2
```

**Comment by lewpayne** [comment]
I hate not having vim or vi.  Sorry... here's the second half of the error...

`C:\Users\lewpa\go\src\github.com\Nitecon\iqfeed_example>go run main.go
System: &iqfeed.SystemMessage{Customer:iqfeed.CustomerData{ServiceType:"", IP:"", Port:0, Token:"", Version:"", Deprecated1:0, VerboseExchanges:"", Deprecated2:"", MaxSymbols:0, Flags:"", Deprecated3:"", Deprecated4:""}, Stats:iqfeed.SystemStats{ServerIP:"", ServerPort:0, MaxSymbols:0, NumberOfSymbols:0, ClientsConnected:0, SecondsSinceLastUpdate:0, Reconnections:0, AttemptedReconnections:0, StartTime:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, MarketTime:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, Status:"", IQFeedVersion:"", LoginID:"", TotalKBsRecv:0, KBsPerSecRecv:0, AvgKBsPerSecRecv:0, TotalKBsSent:0, KBsPerSecSent:0, AvgKBsPerSecSent:0}}
System: &iqfeed.SystemMessage{Customer:iqfeed.CustomerData{ServiceType:"", IP:"", Port:0, Token:"", Version:"", Deprecated1:0, VerboseExchanges:"", Deprecated2:"", MaxSymbols:0, Flags:"", Deprecated3:"", Deprecated4:""}, Stats:iqfeed.SystemStats{ServerIP:"", ServerPort:0, MaxSymbols:0, NumberOfSymbols:0, ClientsConnected:0, SecondsSinceLastUpdate:0, Reconnections:0, AttemptedReconnections:0, StartTime:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, MarketTime:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, Status:"", IQFeedVersion:"", LoginID:"", TotalKBsRecv:0, KBsPerSecRecv:0, AvgKBsPerSecRecv:0, TotalKBsSent:0, KBsPerSecSent:0, AvgKBsPerSecSent:0}}
System: &iqfeed.SystemMessage{Customer:iqfeed.CustomerData{ServiceType:"", IP:"", Port:0, Token:"", Version:"", Deprecated1:0, VerboseExchanges:"", Deprecated2:"", MaxSymbols:0, Flags:"", Deprecated3:"", Deprecated4:""}, Stats:iqfeed.SystemStats{ServerIP:"", ServerPort:0, MaxSymbols:0, NumberOfSymbols:0, ClientsConnected:0, SecondsSinceLastUpdate:0, Reconnections:0, AttemptedReconnections:0, StartTime:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, MarketTime:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, Status:"", IQFeedVersion:"", LoginID:"", TotalKBsRecv:0, KBsPerSecRecv:0, AvgKBsPerSecRecv:0, TotalKBsSent:0, KBsPerSecSent:0, AvgKBsPerSecSent:0}}
System: &iqfeed.SystemMessage{Customer:iqfeed.CustomerData{ServiceType:"", IP:"", Port:0, Token:"", Version:"", Deprecated1:0, VerboseExchanges:"", Deprecated2:"", MaxSymbols:0, Flags:"", Deprecated3:"", Deprecated4:""}, Stats:iqfeed.SystemStats{ServerIP:"", ServerPort:0, MaxSymbols:0, NumberOfSymbols:0, ClientsConnected:0, SecondsSinceLastUpdate:0, Reconnections:0, AttemptedReconnections:0, StartTime:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, MarketTime:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, Status:"", IQFeedVersion:"", LoginID:"", TotalKBsRecv:0, KBsPerSecRecv:0, AvgKBsPerSecRecv:0, TotalKBsSent:0, KBsPerSecSent:0, AvgKBsPerSecSent:0}}
System: &iqfeed.SystemMessage{Customer:iqfeed.CustomerData{ServiceType:"", IP:"", Port:0, Token:"", Version:"", Deprecated1:0, VerboseExchanges:"", Deprecated2:"", MaxSymbols:0, Flags:"", Deprecated3:"", Deprecated4:""}, Stats:iqfeed.SystemStats{ServerIP:"", ServerPort:0, MaxSymbols:0, NumberOfSymbols:0, ClientsConnected:0, SecondsSinceLastUpdate:0, Reconnections:0, AttemptedReconnections:0, StartTime:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, MarketTime:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, Status:"", IQFeedVersion:"", LoginID:"", TotalKBsRecv:0, KBsPerSecRecv:0, AvgKBsPerSecRecv:0, TotalKBsSent:0, KBsPerSecSent:0, AvgKBsPerSecSent:0}}
panic: runtime error: slice bounds out of range
`

**Comment by lewpayne** [comment]
Okay, this time verified the cut-n-paste before reposting.  Here's the second half:

goroutine 20 [running]:
github.com/Nitecon/iqfeed.(*IQC).processReceiver(0xc00008c000, 0xc0000b2978, 0x0, 0x688)
        C:/Users/lewpa/go/src/github.com/Nitecon/iqfeed/iqfeed.go:141 +0x32f
github.com/Nitecon/iqfeed.(*IQC).read(0xc00008c000)
        C:/Users/lewpa/go/src/github.com/Nitecon/iqfeed/iqfeed.go:181 +0x1a6
created by github.com/Nitecon/iqfeed.(*IQC).Start
        C:/Users/lewpa/go/src/github.com/Nitecon/iqfeed/iqfeed.go:268 +0x1d0
exit status 2

**Comment by nitecon** [comment]
Can you take a look if the latest PR fixed this issue?

**Comment by lewpayne** [comment]
I've been working with Federico.  I tested this morning and can confirm his patch fixed the problem.

**Comment by nitecon** [comment]
Thanks @lewpayne and happy holidays!
