### ISSUE TITLE
Can't get it to login

### ISSUE THREAD

**Issue by bryaan** [Nitecon/iqfeed#5]
I am getting connected successfully but I cant get it to Connect().  I beleive I am calling the proper commands in the right order.  All I get back is ` S,KEY,99999`

```
func TestStart(t *testing.T) {
	var iqc IQC
	go func() {
		for {
			select {
			case msg1 := <-iqc.System:
				fmt.Println("received", msg1)
			case msg2 := <-iqc.Errors:
				fmt.Println("received", msg2)
			case msg2 := <-iqc.Regional:
				fmt.Println("received", msg2)
			case msg2 := <-iqc.Updates:
				fmt.Println("received", msg2)
			case msg2 := <-iqc.Time:
				fmt.Println("received", msg2)
			}
		}
	}()
	iqc.Start("localhost:5009")
	fmt.Println("Started IqFeed on Quote Port")
	iqc.SetProtocol("6.2")
	iqc.SetClientName("golang-iqfeed")
	iqc.Connect()
	time.Sleep(30 * time.Second)
}
```

**Comment by nitecon** [comment]
Is your iqfeed application properly up and running?  And do you have the appropriate subscriptions in your account in order to retrieve items from iqfeed?  It's been a few years since I've played with this repo but I remember that being an issue.
